streams {

    ## Stream down events from our friend relays

    friends {
        dir = "down"
#        pluginDown = "/app/write-policy.py"
	filter = { "kinds": [3,1984,10000 ] }
        urls = [
            "wss://wot.grapevine.network",
        ]
    }

}
